application: your-app-id
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico
  secure: always
- url: /static
  static_dir: static
  secure: always
# Endpoints handler
- url: /_ah/spi/.*
  script: helloendpoints_api.app
  secure: always
- url: /
  static_files: static/index.html
  upload: static/index\.html
  secure: always

skip_files:
- ^(.*/)*#.*#$
- ^(.*/)*.*~$
- ^(.*/)*.*\.py[co]$
- ^(.*/)*.*/RCS/.*$
- ^(.*/)*\..*$
- ^(.*/)*(node_modules/.*)$
- ^(.*/)*(test/.*)$
- ^(.*/)*(examples/.*)$
- ^(.*/)*(.*\.json)$
- ^(.*/)*(README.*)$
- ^(.*/)*(readme.*)$
- ^(.*/)*(requirements.txt)$
- ^(.*/)*(LICENSE)$
# TODO: create paver job to uncomment the lines below for appengine deployment
# they must remain commented for local development since venv is the Python interpreter used
# however, when deployed, the app only needs the third-party libraries in venv/lib/python2.7/site-packages
#- ^venv/bin/(.*/)*.*$
#- ^venv/include/(.*/)*.*$
#- ^venv/lib/python2\.7/[^/]*\.(py|txt)$
#- ^venv/lib/python2\.7/config/(.*/)*.*$
#- ^venv/lib/python2\.7/distutils/(.*/)*.*$
#- ^venv/lib/python2\.7/encodings/(.*/)*.*$
#- ^venv/lib/python2\.7/lib-dynload/(.*/)*.*$

libraries:
- name: webapp2
  version: "2.5.2"
- name: pycrypto
  version: latest
- name: endpoints
  version: 1.0
