application: ud859-python-rmw
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
# Endpoints handler
- url: /_ah/spi/.*
  script: conference.conference_api.app
  secure: always
#  login: required
- url: /
  static_files: webapp/index.html
  upload: webapp/index\.html
  secure: always
- url: /css
  static_dir: webapp/css
  secure: always
- url: /fonts
  static_dir: webapp/fonts
  secure: always
- url: /img
  static_dir: webapp/img
  secure: always
- url: /js
  static_dir: webapp/js
  secure: always
- url: /partials
  static_dir: webapp/partials
  secure: always

skip_files:
- ^(.*/)*#.*#$
- ^(.*/)*.*~$
- ^(.*/)*.*\.py[co]$
- ^(.*/)*.*/RCS/.*$
- ^(.*/)*\..*$
- ^(.*/)*(node_modules/.*)$
- ^(.*/)*(test/.*)$
- ^(.*/)*(examples/.*)$
- ^(.*/)*(.*\.json)$
- ^(.*/)*(README.*)$
- ^(.*/)*(readme.*)$
- ^(.*/)*(requirements.txt)$
- ^(.*/)*(LICENSE)$
# TODO: create paver job to uncomment the lines below for appengine deployment
# they must remain commented for local development since venv is the Python interpreter used
# however, when deployed, the app only needs the third-party libraries in venv/lib/python2.7/site-packages
#- ^venv/bin/(.*/)*.*$
#- ^venv/include/(.*/)*.*$
#- ^venv/lib/python2\.7/[^/]*\.(py|txt)$
#- ^venv/lib/python2\.7/config/(.*/)*.*$
#- ^venv/lib/python2\.7/distutils/(.*/)*.*$
#- ^venv/lib/python2\.7/encodings/(.*/)*.*$
#- ^venv/lib/python2\.7/lib-dynload/(.*/)*.*$

libraries:
#- name: webapp2
#  version: "2.5.2"
- name: pycrypto
  version: latest
- name: endpoints
  version: 1.0
